## **Filling Missing Values by Mean Values**

In [88]:
#just for creating null values
import numpy as np
my_list = [3,5,8,4, np.nan,8,4,5,12,5,7,8,np.nan,6,2,6,13,np.nan,5,3,2, 6]

In [89]:
#function to sum values
def sum_values(giveme):
  sum_i = 0
  for i in giveme:
    sum_i = sum_i + i;
  return sum_i

In [90]:
#function to  fill missing values using mean

def handle_me_by_mean (my_list):

  #creating necessary variables here
  list_sum = 0
  temp_1 = []
  temp_2 = []
  average = 0.0
  filled_list = []

  #fconvert to string
  temp_1 = [str(x) for x in my_list]
  #taking all values in temp 2 which are not null
  temp_2 = [x for x in temp_1 if x != 'nan']

  for i in temp_2:
    #converting temp_2 to integer
    i=int(i)
    list_sum += i

    #taking average
  average = list_sum/len(temp_2)
  average = round(average)
  #converting origional list to float values
  temp_1 = [float(x) for x in temp_1]
  for i in temp_1:
    if i==float(i):
      filled_list.append(i)
    else:
      filled_list.append(average)
  return filled_list

In [98]:
print("Output list after filling missing values by mean values is: \n ", handle_me_by_mean(my_list))

Output list after filling missing values by mean values is:
  [3.0, 5.0, 8.0, 4.0, 6, 8.0, 4.0, 5.0, 12.0, 5.0, 7.0, 8.0, 6, 6.0, 2.0, 6.0, 13.0, 6, 5.0, 3.0, 2.0, 6.0]

Filling Missing Values by Using Median

In [99]:

Median_list = [1, 2, 3, np.nan,2,9,3,7,6,9,np.nan,6,4, 5,np.nan]

In [92]:
def sort_list(my_list):
  new_list = []
  while my_list:
    min = my_list[0]  
    for x in my_list: 
        if x < min:
            min = x
    new_list.append(min)
    my_list.remove(min)    
  return new_list

In [93]:
def claculate_median(my_list):
  temp_1 = []
  temp_2 = []
  results = []
  results.clear()
  N = len(my_list)

  sorted_list = sort_list(my_list)
   #convert to strings
  temp_1 = [str(x) for x in sorted_list]
  #taking only real values
  temp_2 = [x for x in temp_1 if x != 'nan']
  
  for i in temp_2:
    #convert to integers
    i=int(i)
  if N % 2 == 0:
    med_1 = sorted_list[N//2]
    med_2 = sorted_list[N//2 - 1]
    median = (med_1 + med_2)/2
  else:
    median = sorted_list[N//2]
    temp_1 = [float(x) for x in temp_1]
  for i in temp_1:
    if i==float(i):
      results.append(i)
    else:
       results.append(median)
  return results

In [94]:
print("Output list after filling missing values by mean values is: \n ",claculate_median(Median_list) )

Output list after filling missing values by mean values is:
  [1.0, 2.0, 2.0, 3.0, 5, 3.0, 4.0, 5.0, 6.0, 6.0, 7.0, 9.0, 9.0, 5, 5]

## **Filling Missing Values Using Mode**

In [95]:
My_List_3 = [np.nan,6,9,9,9,7,6,9,np.nan,6,4, 5,np.nan]

temp_1 = [str(x) for x in My_List_3]                                    
temp_2 = [x for x in temp_1 if x != 'nan']
temp_2


#to sort the list
sorted_list = sort_list(temp_2)
m_list = []
i = 0
while i < len(sorted_list) :
  m_list.append(sorted_list.count(sorted_list[i]))
  i += 1
#making dictionaries
dict_1 = dict(zip(temp_2, m_list))
dict_2 = {k for (k,v) in dict_1.items() if v == max(sorted_list) }

print( "Mode(s) is/are :" + str(dict_2))

empty_mode=[]
l_list = [float(x) for x in My_List_3]
for i in l_list:
  if i==float(i):
    empty_mode.append(i)
  else:
    empty_mode.append(dict_2)
empty_mode

Mode(s) is/are :set()

[set(), 6.0, 9.0, 9.0, 9.0, 7.0, 6.0, 9.0, set(), 6.0, 4.0, 5.0, set()]